💚Update GitHub Actions

diff --git a/.github/workflows/dependabot_prch.yml b/.github/workflows/dependabot_prch.yml
--- a/.github/workflows/dependabot_prch.yml
+++ b/.github/workflows/dependabot_prch.yml
@@ -1,11 +1,15 @@
 name: Dependabot PR Check
 
 # ワークフローの処理の流れ:
-# 1. トリガー条件: main ブランチへのプルリクエスト
+# 1. トリガー条件:
+#    - mainブランチへのプルリクエスト時
+#    - Dependabotによる実行であること
+#    - コミットメッセージが"Bump version"で始まっていないこと
+#    - ブランチ名に"version-update"が含まれていないこと
 # 2. ジョブの条件判定: Dependabot によるPRかチェック
-# 3. 環境設定: Ubuntu、タイムゾーン設定
+# 3. OS毎の環境設定
 # 4. リポジトリのチェックアウト
-# 5. Python環境のセットアップ (3.12)
+# 5. Python環境のセットアップ (3.11,3.12)
 # 6. 依存関係のキャッシュ
 # 7. Poetry のインストール
 # 8. プロジェクト依存関係のインストール
@@ -14,43 +18,97 @@ name: Dependabot PR Check
 
 on:
   pull_request:
-    branches: [ main ]
+    branches: "main"
 
 jobs:
-  dependabot-check:
-    if: ${{ github.actor == 'dependabot[bot]' }}
-    runs-on: ubuntu-latest
+  test:
+    if: github.actor == 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update')
+    strategy:
+      matrix:
+        os: [macos-13, ubuntu-latest, windows-latest]
+        python-version: ['3.11', '3.12']
+    runs-on: ${{ matrix.os }}
     env:
       TZ: 'Asia/Tokyo'
+    permissions:
+      contents: write
+      pull-requests: write
     steps:
       - uses: actions/checkout@v4
-
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.12'
-
+          python-version: ${{matrix.python-version}}
+      - name: Set timezone
+        uses: szenius/set-timezone@v2.0
+        with:
+          timezoneLinux: "Asia/Tokyo"
+          timezoneMacos: "Asia/Tokyo"
+          timezoneWindows: "Tokyo Standard Time"
+      - name: Check timezone
+        shell: bash
+        run: |
+          echo "System date: $(date)"
+          echo "TZ environment variable: $TZ"
+          python -c "import datetime, platform; print(f'Python timezone: {datetime.datetime.now().astimezone().tzinfo}'); print(f'OS: {platform.system()}')"
+      - name: Install poetry
+        run: pip install poetry
       - name: Cache dependencies
         uses: actions/cache@v4
         with:
           path: ~/.cache/pypoetry
           key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
-
-      - name: Install poetry
-        run: pip install poetry
-
       - name: Install dependencies
         run: poetry install
-
       - name: Run tests
-        run: poetry run pytest
-
-      - name: Print final status
-        if: always()
+        #run: poetry run pytest --durations=0 --junitxml=pytest.xml --cov-report=term-missing --cov=project_a tests/ | tee pytest-coverage.txt
+        run: poetry run task test_gh_action_term
+      - name: Pytest coverage comment
+        id: coverageComment
+        uses: MishaKav/pytest-coverage-comment@main
+        with:
+          hide-comment: true
+          pytest-coverage-path: ./pytest-coverage.txt
+          junitxml-path: ./pytest.xml
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check test results
+        if: steps.pytest.outcome == 'failure'
         run: |
-          echo "Final job status: ${{ job.status }}"
-          echo "PR link: ${{ github.event.pull_request.html_url }}"
-          if [ "${{ job.status }}" = "failure" ]; then
-            echo "Tests failed. Please check the test results and fix any issues before merging."
-            exit 1
-          fi
+          echo "Tests failed. This will be reported in the workflow summary."
+          echo "::warning::Tests failed on ${{ matrix.os }} with Python ${{ matrix.python-version }}"
+      - name: Write job summary
+        id: check_status
+        shell: bash
+        run: |
+          echo -e ${{ steps.coverageComment.outputs.summaryReport }} >> $GITHUB_STEP_SUMMARY
+
+  check_all_tests:
+    needs: test
+    runs-on: ubuntu-latest
+    if: github.actor == 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update')
+    steps:
+      - name: Check test results
+        if: contains(needs.test.result, 'failure')
+        run: |
+          echo "Some tests failed. Please check the test results and fix any issues before merging."
+          exit 1
+
+  send_notification:
+    needs: [test, check_all_tests]
+    runs-on: ubuntu-latest
+    if: github.actor == 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update')
+    steps:
+      # https://docs.github.com/ja/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-an-environment
+      - name: Send LINE Notify
+        env:
+          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
+        run: |
+          status="${{ contains(needs.test.result, 'failure') && 'FAILED' || 'SUCCESS' }}"
+          message="'dependabot_prch' workflow completed with status: $status
+
+          Check URL:
+          https://github.com/7rikazhexde/trial-test/actions/workflows/dependabot_prch.yml"
+
+          curl -X POST https://notify-api.line.me/api/notify \
+            -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
+            -F "message=${message}"
