:green_heart:Bulk delete files for workflow testing

diff --git a/.github/workflows/test_pytest-cov-report_deploy_multi_os.yml b/.github/workflows/test_pytest-cov-report_deploy_multi_os.yml
--- a/.github/workflows/test_pytest-cov-report_deploy_multi_os.yml
+++ b/.github/workflows/test_pytest-cov-report_deploy_multi_os.yml
@@ -3,23 +3,24 @@ name: pytest-cov Report and Deploy Multi-OS
 # ワークフローの処理の流れ:
 # 1. トリガー条件:
 #    - pytest-testmon ワークフローの完了後に repository_dispatch イベントで起動
-# 2. 複数の環境（OS、Pythonバージョン）でのテスト実行
+# 2. 複数の環境（OS、Pythonバージョン）でのセットアップ
 #    - Ubuntu, macOS, Windowsの最新バージョンで実行
 #    - Python 3.11と3.12を使用
-#    - testmonの結果に基づいてテストをスキップするかどうかを確認
-# 3. pytest-covを使用してカバレッジレポートを生成
+# 3. 各OS・Pythonバージョンごとに個別の.testmondataファイルを取得
+# 4. testmonの結果に基づいてテストをスキップするかどうかを確認
+# 5. pytest-covを使用してカバレッジレポートを生成
 #    - 各OS環境とPythonバージョンごとに別々のレポートを生成
-# 4. カバレッジ結果のアップロード
+# 6. カバレッジ結果のアップロード
 #    - 常に実行（テストが失敗した場合も含む）
-# 5. 全テスト結果の確認
+# 7. 全テスト結果の確認
 #    - いずれかのテストが失敗した場合、エラーを報告
-# 6. GitHub Pagesへのデプロイ
+# 8. GitHub Pagesへのデプロイ
 #    - すべてのテストが成功した場合のみ実行
 #    - 変更がある場合のみ実際にデプロイを行う
 #    - リモートの最新の変更を取得し、コンフリクトを解決してからプッシュ
-# 7. デプロイしたレポートのURL生成
-# 8. 変更の有無に応じたLINE通知の送信
-#    - 変更があった場合と変更がなかった場合で異なるメッセージを送信
+# 9. デプロイしたレポートのURL生成
+# 10. 変更の有無に応じたLINE通知の送信
+#     - 変更があった場合と変更がなかった場合で異なるメッセージを送信
 
 on:
   repository_dispatch:
@@ -27,7 +28,6 @@ on:
 
 jobs:
   test-and-coverage:
-    #if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
     strategy:
       matrix:
         os: [ubuntu-latest, macos-13, windows-latest]
@@ -39,35 +39,70 @@ jobs:
       contents: write
       pull-requests: write
     steps:
-      - uses: actions/checkout@v4.2.0
+      - name: Checkout repository
+        uses: actions/checkout@v4.2.0
+        with:
+          fetch-depth: 0
+
       - name: Set up Python
         uses: actions/setup-python@v5.2.0
         with:
           python-version: ${{ matrix.python-version }}
+
       - name: Set timezone
         uses: szenius/set-timezone@v2.0
         with:
           timezoneLinux: "Asia/Tokyo"
           timezoneMacos: "Asia/Tokyo"
           timezoneWindows: "Tokyo Standard Time"
-      # 新しく追加するステップ：testmonの結果に基づいてテストをスキップするかどうかを確認
-      - name: Check if tests should be executed
-        shell: bash
-        run: |
-          if [ "${{ github.event.client_payload.skip_tests }}" = "true" ]; then
-            echo "Tests skipped based on testmon results"
-            exit 0
-          fi
+
       - name: Install poetry
         run: pip install poetry
+
       - name: Install dependencies
         run: poetry install
+
+      - name: Fetch testmon data
+        shell: bash
+        run: |
+          echo "Fetching testmon data..."
+          git fetch origin ghpages:ghpages || true
+          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
+          git checkout ghpages -- $folder_name/.testmondata || true
+          if [ -f $folder_name/.testmondata ]; then
+            echo "Testmon data found. Moving to current directory."
+            mv $folder_name/.testmondata .testmondata
+          else
+            echo "No testmon data found for ${{ matrix.os }} with Python ${{ matrix.python-version }}."
+          fi
+        continue-on-error: true
+
+      - name: Check if tests should be executed
+        id: check_tests
+        shell: bash
+        run: |
+          if [ -f .testmondata ] && [ "${{ github.event.client_payload.skip_tests }}" != "true" ]; then
+            echo "Running pytest-testmon to check if tests should be executed..."
+            if poetry run pytest --testmon --testmon-noselect -v | grep -q "collected 0 items"; then
+              echo "No tests need to be executed."
+              echo "skip_tests=true" >> $GITHUB_OUTPUT
+            else
+              echo "Tests need to be executed."
+              echo "skip_tests=false" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "No .testmondata file found or tests are forced to run."
+            echo "skip_tests=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: Run tests with pytest-cov
+        if: steps.check_tests.outputs.skip_tests != 'true'
         id: pytest-cov
         run: |
           mkdir -p htmlcov_${{ matrix.os }}_python_${{ matrix.python-version }}
           poetry run pytest --cov=project_a --cov-report=html:htmlcov_${{ matrix.os }}_python_${{ matrix.python-version }}
         shell: bash
+
       - name: Upload pytest-cov results
         uses: actions/upload-artifact@v4.4.0
         with:
@@ -77,7 +112,6 @@ jobs:
 
   check_all_tests:
     needs: test-and-coverage
-    #if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
     runs-on: ubuntu-latest
     steps:
       - name: Check test results
@@ -88,20 +122,23 @@ jobs:
 
   deploy:
     needs: [test-and-coverage, check_all_tests]
-    #if: github.actor != 'dependabot[bot]' && (github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version'))
     runs-on: ubuntu-latest
     outputs:
       deploy_status: ${{ steps.check_and_deploy.outputs.deploy_status }}
     steps:
-      - uses: actions/checkout@v4.2.0
+      - name: Checkout repository
+        uses: actions/checkout@v4.2.0
         with:
           fetch-depth: 0
+
       - name: Download pytest-cov artifacts
         uses: actions/download-artifact@v4.1.8
+
       - name: Setup Git
         run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
+
       - name: Check and Deploy to GitHub Pages
         id: check_and_deploy
         run: |
@@ -130,17 +167,18 @@ jobs:
           done
 
           if [ "$changes_made" = true ]; then
-           git commit -m "Update pytest-cov reports on GitHub Pages"
-           # Try to push changes, if fails, pull and retry
-           if ! git push origin ghpages; then
-             git pull origin ghpages --rebase
-             git push origin ghpages
-           fi
-           echo "deploy_status=updated" >> $GITHUB_OUTPUT
+            git commit -m "Update pytest-cov reports on GitHub Pages"
+            # Try to push changes, if fails, pull and retry
+            if ! git push origin ghpages; then
+              git pull origin ghpages --rebase
+              git push origin ghpages
+            fi
+            echo "deploy_status=updated" >> $GITHUB_OUTPUT
           else
             echo "No changes to commit"
             echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
           fi
+
       - name: Generate URL list
         id: generate_url_list
         run: |
@@ -157,6 +195,7 @@ jobs:
           echo "url_list<<EOF" >> $GITHUB_OUTPUT
           echo -e "$URL_LIST" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
+
       - name: Send LINE Notify (Updated)
         if: steps.check_and_deploy.outputs.deploy_status == 'updated'
         env:
@@ -170,6 +209,7 @@ jobs:
           curl -X POST https://notify-api.line.me/api/notify \
             -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
             -F "message=${message}"
+
       - name: Send LINE Notify (No Changes)
         if: steps.check_and_deploy.outputs.deploy_status == 'unchanged'
         env:
